JFreeChart build requires Java 17
Error:  /home/runner/work/jfreechart/jfreechart/src/test/java/org/jfree/chart/JFreeChartTest.java:[39,30]
cannot access nl.jqno.equalsverifier.EqualsVerifier
  bad class file:
/home/runner/.m2/repository/nl/jqno/equalsverifier/equalsverifier/4.0/equalsverifier-4.0.jar(nl/jqno/equalsverifier/EqualsVerifier.class)
    class file has wrong version 61.0, should be 52.0